services:
  audiobook-tracker:
    build: .
    container_name: audiobook-tracker
    ports:
      - "8241:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    # environment:
    #   - LOG_LEVEL=DEBUG  # DEBUG/INFO/WARNING/ERROR/CRITICAL, default INFO
